Support for gzipped fasta files throughout workflow
nextstrain/ncov-ingest pull request #121
Opened 2021-01-21 00:45 UTC by ttung

### Description of proposed changes    
1. Upload and delta change scripts understand .gz files.  Checksums are still performed on uncompressed data.  This works out well, because we compress at most once, and uncompressing is cheap.
2. `bin/transform-gisaid` will inspect the input to see if it's gzipped.  If so, it unzips it.
3. `bin/transform-gisaid` will use the output filename to decide whether or not to compress it on the fly.

### Testing
Launched a build where we keep most files compressed.  We had an earlier version of the workflow without the nextclade integration, but when rebased, it'll likely be problematic.  However, this workflow can still operate on uncompressed data, so it is backwards compatible.

2021-01-22 18:31 UTC, tsibley commented
Thanks, @ttung! Is this working well for you folks in your own ingests? Did you notice a meaningful time increase due to compression?

Background for the rest of the team/posterity: Tony's change was born out of disk-space issues on GitHub Actions. The Nextstrain team has since moved our ingest to run on AWS Batch (via `nextstrain build` infrastructure) after being triggered by GitHub Actions.

On AWS Batch we're not meaningfully constrained on disk anymore, so I'm not sure trade of disk usage for CPU/wall clock time that compression makes is worth it? That said, this PR doesn't require use of compression, just adds support for it, so we could still accept the PR but not make the compression trade.

2021-01-23 00:13 UTC, ttung commented
It's not meaningfully different because we are compressing during upload-to-s3 anyway.  Decompressing the .gz file takes ~4s on my laptop.

Yes, this does not require you to use compression.

2021-04-02 15:12 UTC, rneher commented
@WandrilleD Do you see any reason why this shouldn't be merged?

2021-04-09 11:17 UTC, WandrilleD commented on bin/transform-gisaid
> +        default="data/gisaid.ndjson.gz",
this looks like a local adaptation. Any reason why we should not use the s3 file there ?

2021-04-09 11:19 UTC, WandrilleD requested changes
I have doubt about the new suggested default value for the gisaid json file name in transform-gisaid. Aside from that everything seems file, especially since it also support non-gzipped files.

2023-03-31 00:08 UTC, closed without merging